Minor fixes

diff --git a/tools/aurex-vtools/install/usr/sbin/vt-backup b/tools/aurex-vtools/install/usr/sbin/vt-backup
--- a/tools/aurex-vtools/install/usr/sbin/vt-backup
+++ b/tools/aurex-vtools/install/usr/sbin/vt-backup
@@ -3,7 +3,7 @@
 # File:		vt-backup
 # Description:	simple virtual machine backup script
 # Authors:	Sandra Villanueva <svillanueva@ausiasmarch.net>
-		Luis Garcia <lgarcia@ausiasmarch.net>
+#		Luis Garcia <lgarcia@ausiasmarch.net>
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -45,11 +45,12 @@ vt_verify_domain_status(){
 
 vt_stop_domain(){
 	VM_NAME="$1"
+	echo "Stopping Domain: $VM_NAME"
 	$VIRSH shutdown "$VM_NAME"
-	MAX_WAIT=5
+	MAX_WAIT=30
 	i=0
 	while ! vt_verify_domain_status "$VM_NAME" && [  $i -le $MAX_WAIT ] ; do
-		sleep 1
+		sleep 2
 		i=$(($i + 1))
 	done
 	vt_verify_domain_status "$VM_NAME" || return 1
@@ -57,6 +58,8 @@ vt_stop_domain(){
 }
 
 vt_start_domain(){
+	VM_NAME="$1"
+	echo "Starting Domain: $VM_NAME"
 	$VIRSH start "$VM_NAME"
 }
 		
@@ -65,7 +68,8 @@ vt_freeze_images(){
 	VM_NAME="$1"
 	CURRENT_PATH="$(pwd)"
 	TIMESTAMP="$(date "+%F_%H%M")"
-	for VM_DISK in $(vt_get_disk_images) ; do
+	echo "Creating new disk images for Domain: $VM_NAME"
+	for VM_DISK in $(vt_get_disk_images "$VM_NAME") ; do
 		DISK_IMG_PATH="$(dirname "$VM_DISK")"
 		DISK_IMG_FILENAME="$(basename "$VM_DISK")"
 		DISK_IMG_NAME="${DISK_IMG_FILENAME%.*}"
@@ -73,7 +77,9 @@ vt_freeze_images(){
 		NEW_DISK_IMG_NAME="${DISK_IMG_NAME}-${TIMESTAMP}.${DISK_IMG_EXT}"
 		cd "$DISK_IMG_PATH"
 		mv "$DISK_IMG_FILENAME" "$NEW_DISK_IMG_NAME"
+		echo "Old $DISK_IMG_FILENAME has been renamed to $NEW_DISK_IMG_NAME"
 		qemu-img create -b "$NEW_DISK_IMG_NAME" -f qcow2 "$DISK_IMG_FILENAME"
+		echo "New $DISK_IMG_FILENAME based on $NEW_DISK_IMG_NAME has been created"
 		DISK_IMG_LIST="$DISK_IMG_LIST $DISK_IMG_PATH/$NEW_DISK_IMG_NAME"
 	done
 	cd "$CURRENT_PATH"
@@ -96,18 +102,30 @@ usage(){
 DEF_BACKUP_DIR="/tmp"
 # DEF_BACKUP_DIR="/srv/data/backup"
 
-VM_NAME"$1"
+VM_NAME="$1"
 shift
 BACKUP_DIR="$1"
 [ "$BACKUP_DIR" ] || BACKUP_DIR="$DEF_BACKUP_DIR"
 
 DISK_IMG_LIST=""
-vt_stop_domain "$VM_NAME" || die "Unable to stop domain: $VM_NAME"
-vt_freeze_images "$VM_NAME" || die "Error creating new disk images for domain: $VM_NAME" 
-vt_start_domain "$VM_NAME" || die "Error starting domain: $VM_NAME"
+VM_START="Y"
+
+if vt_verify_domain_status "$VM_NAME" ; then
+	echo "Domain: $VM_NAME not running"
+	VM_START=""
+else
+	vt_stop_domain "$VM_NAME" || die "Unable to stop domain: $VM_NAME"
+fi
+
+vt_freeze_images "$VM_NAME" || die "Error creating new disk images for domain: $VM_NAME"
+
+if [ "$VM_START" ] ; then
+	vt_start_domain "$VM_NAME" || die "Error starting domain: $VM_NAME"
+fi
+
 [ "$DISK_IMG_LIST" ] || die "No disk images to copy"
 
-echo "Copying disk image files: $DISK_IMG_LIST"
+echo "Copying disk image files: $DISK_IMG_LIST to $BACKUP_DIR"
 cp $DISK_IMG_LIST $BACKUP_DIR || die "Error copying disk images"
 cat << EOF
 Backup completed.
