script updated

diff --git a/tools/wbackup/install/usr/bin/wbackup b/tools/wbackup/install/usr/bin/wbackup
--- a/tools/wbackup/install/usr/bin/wbackup
+++ b/tools/wbackup/install/usr/bin/wbackup
@@ -1,6 +1,6 @@
 #!/bin/sh
 # --------
-# File:		backup-strato
+# File:		wbackup (aka backup-strato)
 # Description:	simple script to backup/synchronize web pages and mysql
 # Authors:	Luis Garcia Gisbert <luisgg@gmail.com>
 #		Sandra Villanueva Gavino <savilga@gmail.com>
@@ -55,43 +55,67 @@ update_last_link(){
 # --------
 # vars
 # --------
-SSH_HOST="ssh.strato.de"
-SSH_USER="ausiasmarch.es"
-MYSQLDUMP_CMD="mysqldump --opt -h rdbms"
-LOGGER_CMD="logger -t backup-strato -s"
-BACKUP_BASE_DIR="$HOME/backup-strato"
-LAST_BACKUP="LAST-BACKUP"
 
-WEB_REMOTE_DIR="portal"
-WEB_LOCAL_DIR="portal"
+CFG_DIR="/etc/wbackup"
+WB_CONF="$CFG_DIR/sites.d"
 
 # --------
 # main
 # --------
 
-$LOGGER_CMD "BACKUP STARTED"
+WB_SITES="$(find "$WB_CONF" -xtype f -name "*conf")"
+for WB_SITE in $WB_SITES ; do
+	# reset values for required variables
+	SSH_HOST=""
+	SSH_USER=""
+	MYSQLDUMP_CMD="mysqldump --opt"
+	BACKUP_NAME="$(basename "$WB_SITE" ".conf" )"
+	WEB_REMOTE_DIR=""
+	WEB_LOCAL_DIR=""
+	WB_BASE_DIR="/var/wbackup"
+	LAST_BACKUP="LAST-BACKUP"
+	
+	# set a common defaul to for MYSQL_HOST
+	MYSQL_HOST="localhost"
+	#SSH_HOST="ssh.strato.de"
+	#SSH_USER="ausiasmarch.es"
+	#MYSQLDUMP_CMD="mysqldump --opt -h rdbms"
+	#WEB_REMOTE_DIR="portal"
+	#WEB_LOCAL_DIR="portal"
+	# source credentials file
+	[ -r "$WB_SITE" ] || die "$WB_SITE not found"
+	. $WB_SITE
 
-# source credentials file
-CR_FILE="$HOME/.mysqldump.strato"
-[ -r "$CR_FILE" ] || die "$CR_FILE not found"
-. $CR_FILE
+	LOGGER_CMD="logger -t wbackup-${BACKUP_NAME} -s"
+	BACKUP_BASE_DIR="$WB_BASE_DIR/wbackup-${BACKUP_NAME}"
 
-# verify required variables
-if [ -z "$MYSQL_USER" ] || [ -z "$MYSQL_PASS" ] || [ -z "$MYSQL_DB" ] ; then
-	die "Verify required variables"
-fi
 
-MYSQLDUMP_CMD="$MYSQLDUMP_CMD -u $MYSQL_USER -p$MYSQL_PASS $MYSQL_DB"
 
-# do the backup
-TIMESTAMP="$(date "+%Y-%m-%d_%H%M%S")"
-BACKUP_DIR="$BACKUP_BASE_DIR/$TIMESTAMP"
-mkdir -p "$BACKUP_DIR"
+	$LOGGER_CMD "BACKUP STARTED"
 
-mysql_dump "$BACKUP_DIR" || die "mysql backup FAILED"
-web_backup "$BACKUP_DIR" || die "web backup FAILED"
 
-update_last_link "$BACKUP_DIR"
 
-$LOGGER_CMD "BACKUP COMPLETED"
+	MYSQLDUMP_CMD="$MYSQLDUMP_CMD -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASS $MYSQL_DB"
+
+	# do the backup
+	TIMESTAMP="$(date "+%Y-%m-%d_%H%M%S")"
+	BACKUP_DIR="$BACKUP_BASE_DIR/$TIMESTAMP"
+	mkdir -p "$BACKUP_DIR"
+
+	# verify required variables
+	if [ -z "$MYSQL_USER" ] || [ -z "$MYSQL_PASS" ] || [ -z "$MYSQL_DB" ] || [ -z "$MYSQL_HOST" ] ; then
+		$LOGGER_CMD "Skipping mysql backup (no variables found)"
+	else
+		mysql_dump "$BACKUP_DIR" || die "mysql backup FAILED"
+	fi
+	if [ -z "$WEB_REMOTE_DIR" ] || [ -z "$WEB_LOCAL_DIR" ] ; then
+		$LOGGER_CMD "Skipping web backup (no variables found)"
+	else
+		web_backup "$BACKUP_DIR" || die "web backup FAILED"
+	fi
+
+	update_last_link "$BACKUP_DIR"
+
+	$LOGGER_CMD "BACKUP COMPLETED"
+done
 
